// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Event {
  id: bigint;
  title: string;
  description: string | null;
  color: string | null;
  start_date: bigint;
  end_date: bigint;
  location_lng: number | null;
  location_lat: number | null;
  created_at: bigint;
  edited_at: bigint | null;
}
