// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PostEvent {
  title: string;
  description: string | null;
  color: string | null;
  startDate: bigint;
  endDate: bigint;
  locationLng: number | null;
  locationLat: number | null;
  createdAt: bigint;
}
