name: Lint backend

on:
  push:

jobs:
  lint:
    name: Lint backend
    runs-on: ubuntu-latest
    steps:

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            backend/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> rustup.sh 
      - run: chmod +x rustup.sh
      - run: yes 1 | ./rustup.sh
      - run: rustup update stable

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
